service: steam-app


provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-north-1
  timeout: 30
package:
  exclude:
    - 'src/**'

functions:
  testLambda:
    handler: dist/src/controllers/testController.testLambda
    events:
      - http:
          path: /test
          method: get  

plugins:
  - serverless-offline
