export enum RESPONSE_MESSAGES {
    SUCCESS = "SUCCESS",
    CREATED= "CREATED",
    FAILURE = "FAILURE",
    NOT_FOUND = "NOT_FOUND",
    FORBIDDEN = "FORBIDDEN",
    BAD_REQUEST = "BAD_REQUEST",
    CONFLICT = "CONFLICT"
}